package dataroot

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Exit codes for factory commands.
const (
	ExitSuccess          = 0
	ExitPartial          = 10
	ExitBlocked          = 20
	ExitFailed           = 30
	ExitBudgetExhausted  = 40
	ExitNeedsHumanReview = 50
)

// ExecutionClass records how a stage was satisfied.
type ExecutionClass string

const (
	ClassReal     ExecutionClass = "real"
	ClassFixture  ExecutionClass = "fixture"
	ClassMock     ExecutionClass = "mock"
	ClassReplayed ExecutionClass = "replayed"
	ClassPartial  ExecutionClass = "partial"
)

// BlockedResult is a first-class outcome when an external dependency prevents the real path.
type BlockedResult struct {
	SchemaVersion     int       `json:"schema_version"`
	Dependency        string    `json:"dependency"`
	Operation         string    `json:"operation"`
	Classification    string    `json:"classification"`
	SanitizedError    string    `json:"sanitized_error"`
	StagesCompleted   []string  `json:"stages_completed"`
	StagesNotRun      []string  `json:"stages_not_run"`
	PartialArtifacts  []string  `json:"partial_artifacts,omitempty"`
	RetrySafe         bool      `json:"retry_safe"`
	NextAction        string    `json:"next_action"`
	At                time.Time `json:"at"`
}

// WriteBlocked persists a blocked result and returns ExitBlocked.
func WriteBlocked(dataRoot string, runID string, b BlockedResult) (string, error) {
	if b.SchemaVersion == 0 {
		b.SchemaVersion = 1
	}
	if b.At.IsZero() {
		b.At = time.Now().UTC()
	}
	dir := filepath.Join(dataRoot, "runs", runID, "blocked")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, fmt.Sprintf("%d.json", b.At.UnixNano()))
	raw, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return "", err
	}
	// Also index under dataRoot/blocked for status.
	idxDir := filepath.Join(dataRoot, "blocked")
	_ = os.MkdirAll(idxDir, 0o755)
	idxPath := filepath.Join(idxDir, fmt.Sprintf("%s-%d.json", runID, b.At.UnixNano()))
	_ = os.WriteFile(idxPath, raw, 0o644)
	return path, nil
}

// ListBlocked returns unresolved blocked results under the data root.
func ListBlocked(dataRoot string) ([]BlockedResult, error) {
	dir := filepath.Join(dataRoot, "blocked")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []BlockedResult
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var b BlockedResult
		if json.Unmarshal(raw, &b) == nil {
			out = append(out, b)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].At.Before(out[j].At) })
	return out, nil
}

// RenderSTATUS generates STATUS.md content from blocked results.
func RenderSTATUS(blocked []BlockedResult) string {
	var b strings.Builder
	b.WriteString("# factory STATUS\n\n")
	b.WriteString("Generated by `factory status`. Blocked outcomes are not test failures.\n\n")
	if len(blocked) == 0 {
		b.WriteString("No unresolved blocked results.\n")
		return b.String()
	}
	byDep := map[string][]BlockedResult{}
	for _, bl := range blocked {
		byDep[bl.Dependency] = append(byDep[bl.Dependency], bl)
	}
	deps := make([]string, 0, len(byDep))
	for d := range byDep {
		deps = append(deps, d)
	}
	sort.Strings(deps)
	for _, d := range deps {
		b.WriteString("## ")
		b.WriteString(d)
		b.WriteString("\n\n")
		for _, bl := range byDep[d] {
			fmt.Fprintf(&b, "- **%s** (%s): %s\n  - next: %s\n", bl.Operation, bl.Classification, bl.SanitizedError, bl.NextAction)
		}
		b.WriteString("\n")
	}
	return b.String()
}
