package optimizer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/adversarylabs/adversary/internal/train/critic"
)

// Proposal is an optimizer output: patch + experiment record (no merge).
type Proposal struct {
	ID              string    `json:"id"`
	TargetAdversary string    `json:"target_adversary"`
	BaseVersion     string    `json:"base_version"`
	HypothesisIDs   []string  `json:"hypothesis_ids"`
	Hypothesis      string    `json:"hypothesis"`
	PatchPath       string    `json:"patch_path"`
	PatchContent    string    `json:"-"`
	ChangeSurface   string    `json:"change_surface"`
	CreatedAt       time.Time `json:"created_at"`
	Status          string    `json:"status"` // proposed
}

// ExperimentRecord is the experiment manifest (lifecycle starts at proposed).
type ExperimentRecord struct {
	ID              string    `json:"id"`
	Status          string    `json:"status"` // proposed | running | accepted | rejected | needs-human-review
	TargetAdversary string    `json:"target_adversary"`
	BaseVersion     string    `json:"base_version"`
	CandidateLabel  string    `json:"candidate_label"`
	Hypothesis      string    `json:"hypothesis"`
	HypothesisIDs   []string  `json:"hypothesis_ids"`
	PatchPath       string    `json:"patch_path"`
	CaseIDs         []string  `json:"case_ids"`
	CreatedAt       time.Time `json:"created_at"`
	Decision        string    `json:"decision,omitempty"` // empty until human decides
	DecisionNotes   string    `json:"decision_notes,omitempty"`
}

// Propose builds a patch and experiment record from critic hypotheses.
// The patch is a documentation/prompt guidance delta file suitable for applying to engineering-review.
func Propose(hypotheses []critic.Hypothesis, target, baseVersion string, caseIDs []string, outDir string) (*Proposal, *ExperimentRecord, error) {
	if target == "" {
		target = "engineering-review"
	}
	if baseVersion == "" {
		baseVersion = "local"
	}
	if len(hypotheses) == 0 {
		return nil, nil, fmt.Errorf("no hypotheses to propose from")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, nil, err
	}

	// Prefer first non-synthesis hypothesis, else first.
	primary := hypotheses[0]
	for _, h := range hypotheses {
		if h.ID != "h-synthesis" {
			primary = h
			break
		}
	}

	id := fmt.Sprintf("exp-%d", time.Now().UTC().Unix())
	patchName := id + ".patch"
	patchPath := filepath.Join(outDir, patchName)
	patchBody := buildPatch(primary, target)
	if err := os.WriteFile(patchPath, []byte(patchBody), 0o644); err != nil {
		return nil, nil, err
	}

	// Also write a FACTORY_IMPROVEMENT.md snippet the experimenter can drop into the adversary tree.
	snippetPath := filepath.Join(outDir, id+"-IMPROVEMENT.md")
	snippet := buildImprovementMarkdown(primary)
	if err := os.WriteFile(snippetPath, []byte(snippet), 0o644); err != nil {
		return nil, nil, err
	}

	p := &Proposal{
		ID:              id,
		TargetAdversary: target,
		BaseVersion:     baseVersion,
		HypothesisIDs:   hypothesisIDs(hypotheses),
		Hypothesis:      primary.GeneralizedFailureMode,
		PatchPath:       patchPath,
		PatchContent:    patchBody,
		ChangeSurface:   primary.SuggestedChangeSurface,
		CreatedAt:       time.Now().UTC(),
		Status:          "proposed",
	}
	rec := &ExperimentRecord{
		ID:              id,
		Status:          "proposed",
		TargetAdversary: target,
		BaseVersion:     baseVersion,
		CandidateLabel:  id + "-candidate",
		Hypothesis:      primary.GeneralizedFailureMode + "\n\nPrinciple: " + primary.Principle,
		HypothesisIDs:   p.HypothesisIDs,
		PatchPath:       patchPath,
		CaseIDs:         caseIDs,
		CreatedAt:       p.CreatedAt,
		// Decision intentionally empty — human only.
	}
	recPath := filepath.Join(outDir, id+".experiment.json")
	if err := writeJSON(recPath, rec); err != nil {
		return nil, nil, err
	}
	if err := writeJSON(filepath.Join(outDir, id+".proposal.json"), p); err != nil {
		return nil, nil, err
	}
	return p, rec, nil
}

func buildPatch(h critic.Hypothesis, target string) string {
	// Unified-diff style patch that adds a factory-driven improvement note.
	// Safe to apply with `git apply` when the file is new, or used as guidance.
	var b strings.Builder
	b.WriteString("*** factory optimizer proposal ***\n")
	fmt.Fprintf(&b, "Target: %s\n", target)
	fmt.Fprintf(&b, "Surface: %s\n\n", h.SuggestedChangeSurface)
	b.WriteString("--- /dev/null\n")
	b.WriteString("+++ b/FACTORY_IMPROVEMENT.md\n")
	b.WriteString("@@ -0,0 +1,20 @@\n")
	for _, line := range strings.Split(buildImprovementMarkdown(h), "\n") {
		b.WriteString("+")
		b.WriteString(line)
		b.WriteString("\n")
	}
	return b.String()
}

func buildImprovementMarkdown(h critic.Hypothesis) string {
	return fmt.Sprintf(`# Factory-proposed improvement

> Generated by adversary-factory optimizer. Human review required before release.

## Observed failure

%s

## Generalized failure mode

%s

## Principle

%s

## Why this is not repository-specific

%s

## Suggested change surface

%s

## Counterexamples to watch

%s
`,
		h.ObservedFailure,
		h.GeneralizedFailureMode,
		h.Principle,
		h.WhyNotRepoSpecific,
		h.SuggestedChangeSurface,
		strings.Join(h.Counterexamples, "\n- "),
	)
}

func hypothesisIDs(hs []critic.Hypothesis) []string {
	var ids []string
	for _, h := range hs {
		ids = append(ids, h.ID)
	}
	return ids
}

func writeJSON(path string, v any) error {
	// local to avoid import cycle issues — use encoding/json
	return writeJSONFile(path, v)
}
