package workspace

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const configStub = `# adversary.train.yaml — edit and commit
# Generated by: adversary train init
#
# Train walks PR review history, grades local packages against human gold,
# and drafts improvements. It does not fine-tune model weights.
# Official catalog packages (when enabled) act as a read-only jury only.

version: 1

# Local (home-grown) packages — the only ones that receive train drafts.
adversaries:
  # Multi-package workspace:
  root: ./adversaries
  # Single package at workspace root instead:
  # path: .
  # Optional: locals that replace an official package id (local always wins).
  # overrides:
  #   go/security: my-security

# Official catalog — grade-only jury (never trained).
official:
  enabled: true
  # auto_pull: true
  # include: []   # empty = all official packages available
  # exclude:
  #   - engineering-review

# History sources — pick one style:
#
# A) Repo catalog (default): list repos to hunt
# B) Author reviews: no repo list; GitHub search for PRs they reviewed
#    discovery: author_reviews
#    authors_only: [mitchellh]
#    # orgs: [hashicorp]   # optional bound
#    # author_roles: [reviewed-by]  # or commenter, author
sources:
  host: github.com
  # discovery: author_reviews
  # org: acme
  # orgs: []
  repos: []
  # languages: [go]
  # since: "2024-01-01"
  # authors_ignore:
  #   - noisy-reviewer
  # authors_only:
  #   - staff-eng-alice
  # author_roles: [reviewed-by]

run:
  max_prs: 50
  max_turns: 200
  # Parallel PR collect (GitHub HTTP API). Default 4; raise carefully to avoid rate limits.
  # Local package runs stay serialized (safe to edit drafts in another turn).
  concurrency: 4

state_dir: .adversary-train
`

// InitOptions controls workspace scaffolding.
type InitOptions struct {
	// Path is the workspace root (default cwd).
	Path string
	// Force overwrites an existing config file.
	Force bool
	// SinglePackage sets adversaries.path: . instead of root: ./adversaries.
	SinglePackage bool
}

// InitResult summarizes what was written.
type InitResult struct {
	Workspace string
	Config    string
	StateDir  string
	Created   bool // true if config was newly written
}

// Init scaffolds adversary.train.yaml, state dir, and gitignore entry.
func Init(opts InitOptions) (InitResult, error) {
	root := opts.Path
	if root == "" {
		wd, err := os.Getwd()
		if err != nil {
			return InitResult{}, err
		}
		root = wd
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return InitResult{}, err
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		return InitResult{}, err
	}

	cfgPath := filepath.Join(abs, DefaultConfigName)
	created := false
	if _, err := os.Stat(cfgPath); err == nil && !opts.Force {
		// leave existing config
	} else if err == nil && opts.Force || os.IsNotExist(err) {
		body := configStub
		if opts.SinglePackage {
			body = strings.Replace(body,
				"  root: ./adversaries\n  # Single package at workspace root instead:\n  # path: .",
				"  # root: ./adversaries\n  path: .",
				1)
		}
		// Detect single package if adversary.yaml at root
		if !opts.SinglePackage {
			if _, e := os.Stat(filepath.Join(abs, "adversary.yaml")); e == nil {
				if _, e2 := os.Stat(filepath.Join(abs, "adversaries")); e2 != nil {
					body = strings.Replace(body,
						"  root: ./adversaries\n  # Single package at workspace root instead:\n  # path: .",
						"  # root: ./adversaries\n  path: .",
						1)
				}
			}
		}
		if err := os.WriteFile(cfgPath, []byte(body), 0o644); err != nil {
			return InitResult{}, err
		}
		created = true
	} else if err != nil {
		return InitResult{}, err
	}

	stateDir := filepath.Join(abs, DefaultStateDir)
	// results.db is created on first train run (SQLite); no results/ tree needed.
	for _, sub := range []string{"", "state", "state/discovery", "runs", "experiments"} {
		if err := os.MkdirAll(filepath.Join(stateDir, sub), 0o755); err != nil {
			return InitResult{}, err
		}
	}

	if err := ensureGitignore(abs); err != nil {
		return InitResult{}, err
	}

	return InitResult{
		Workspace: abs,
		Config:    cfgPath,
		StateDir:  stateDir,
		Created:   created,
	}, nil
}

func ensureGitignore(root string) error {
	path := filepath.Join(root, ".gitignore")
	entry := DefaultStateDir + "/"
	if raw, err := os.ReadFile(path); err == nil {
		if strings.Contains(string(raw), DefaultStateDir) {
			return nil
		}
		var b strings.Builder
		b.Write(raw)
		if len(raw) > 0 && raw[len(raw)-1] != '\n' {
			b.WriteByte('\n')
		}
		b.WriteString("\n# adversary train runtime state\n")
		b.WriteString(entry)
		b.WriteByte('\n')
		return os.WriteFile(path, []byte(b.String()), 0o644)
	} else if !os.IsNotExist(err) {
		return err
	}
	body := fmt.Sprintf("# adversary train runtime state\n%s\n", entry)
	return os.WriteFile(path, []byte(body), 0o644)
}
